### ISSUE TITLE
Connection attributes

### ISSUE THREAD

**Issue by vanous** [jreese/aiosqlite#11]
Thanks for all the work!

If you don't mind, please add

db._conn.row_factory = aiosqlite.core.sqlite3.Row

into your example in readme, took me forever to figure it out :)

thank you

**Comment by jreese** [comment]
Should be easier/nicer to work with now too, just `db.row_factory = aiosqlite.Row`.  Thanks for the feedback! 🍻

**Comment by vanous** [comment]
Wow, thanks you for the fast reaction and an excellent fix!
