### ISSUE TITLE
fetchall() doesn't return anything

### ISSUE THREAD

**Issue by Colink02** [jreese/aiosqlite#16]
### Description
I was working on a discord bot and needed to use aiosqlite for storing configs. however when i check the sqlite database with:
`async def is_guild_owner(ctx):
        async with aiosqlite.connect(vars.database) as conn:
            allowed_roles = await conn.execute(f'''SELECT role_id FROM 'Allowed_roles' WHERE server_id={int(ctx.guild.id)};''')
            if(ctx.message.author == ctx.guild.owner or ctx.message.author.id in await allowed_roles.fetchall()):
                await conn.close()
                return True
            else:
                for role in ctx.message.author.roles:
                    if role.id in await allowed_roles.fetchall():
                        return True
                print("|None of theses: "+ str(ctx.message.author.roles) + " are in: "+ str(await allowed_roles.fetchall()))
                await allowed_roles.close()
                return False`
It returns false everytime and when i print out the allowed_roles.fetchall() it shows an empty list and i know i have a record inside of the database with the proper table.

### Details

* OS: Windows 10
* Python version: Python 3.6.6
* aiosqlite version: 0.7.0
* Can you repro on master? umm no?
* Can you repro in a clean virtualenv? idk how to change environments

**Comment by Colink02** [comment]
Hmm. The list seems to not even have anything inside of it. I did:
`    async with aiosqlite.connect(vars.database) as conn:`
`         allowed_roles = await conn.execute(f'''SELECT role_id FROM 'Allowed_roles' WHERE server_id={int(ctx.guild.id)};''')`
`         tempList = await allowed_roles.fetchall()`
`         print(str(tempList))`
only returns `[]` and thats it
![image](https://user-images.githubusercontent.com/11688661/47623300-cacf2200-dadd-11e8-9704-0d11f3f740a6.png)
Above is whats in the database table

**Comment by jreese** [comment]
I built a simple test of `fetchall()` that runs correctly on my machine (6d55f7da6bf435feab16cf39c2a8793fccc40567 passes on python 3.5+).  Can you verify that these tests pass in your environment, and test your use case with either the standard sqlite3 library and/or the sqlite CLI?  Also, please verify that you're connecting to the same database from both your GUI and the application, and that any data added from the GUI has been correctly committed.

**Comment by Colink02** [comment]
Yes the test do pass. It does not work on the normal sqlite3 library either. however in a sqlite CLI it does return the row. The data has been written to the database file. I tried different ways of inputing the data without a fstring but it still doesn't return anything whatsoever.

**Comment by jreese** [comment]
Sorry to say, but if it's not working with the standard library either, then I don't think this is an issue with aiosqlite, and I'm not sure that I'm able to help you any further.  I'm going to close the issue, but feel free to respond if you have any other questions about aiosqlite, and I'll do my best to answer them.

**Comment by Colink02** [comment]
I have found the issue no worrys. Didn't know you could only use fetchall() once. Just found out :D thanks for the help!
