### ISSUE TITLE
Request to release 0.7.1

### ISSUE THREAD

**Issue by discosultan** [jreese/aiosqlite#17]
Would be nice to have the following changes published with a new version:

- [Avoid polling the Connection thread.](https://github.com/jreese/aiosqlite/commit/72fd3db5ab07128ee44de5b7f08dad3c8bb0765f)
- [Bugfix, exceptions were not safely set from the sqlite thread.](https://github.com/jreese/aiosqlite/commit/502c683684279af3fd1d38953debd3b4f80da7f4)

**Comment by jreese** [comment]
Released as v0.8.0
