### ISSUE TITLE
Recommended way load sqlite extensions?

### ISSUE THREAD

**Issue by arlyon** [jreese/aiosqlite#22]
### Description

I'm trying to use spatialite, and need to load an extension to do so. In `sqlite3`, this is done with the `enable_load_extension` function, however it seems like that isn't exposed in `aiosqlite`. I'm able to implement this myself if it isn't currently possible, but would appreciate some pointers.

Thanks! :)

### Details

* OS: MacOS
* Python version: 3.6.7
* aiosqlite version: latest

**Comment by jreese** [comment]
The best way would be to add the appropriate shims for `enable_load_extension()` and `load_extension()` to the `Connection` class at https://github.com/jreese/aiosqlite/blob/master/aiosqlite/core.py#L110 - you should be able to follow the pattern used for the various `execute` methods.  Feel free to submit a PR, and I'll review it when I get the opportunity.
