### ISSUE TITLE
How to return an active connection from a function?

### ISSUE THREAD

**Issue by emptyVoid** [jreese/aiosqlite#26]
### Description
I'd like to return a configured connection from a function, something like this:
```python
async def open_or_create():
    # prepare filesystem
    ...
    connection = aiosqlite.connect(filename)
    # create tables if database is empty
    async with connection.execute('PRAGMA user_version') as cursor:
        # prepare database
        ...
    # prepare connection
    ...
    return connection
```
Though apparently ```aiosqlite``` connections do not work outside of ```async with``` clause, and I get a ```ValueError``` (no active connection) exception on ``` connection.execute```. Moreover, adding ```async with``` to ```aiosqlite.connect``` line results in a broken connection getting returned to the caller, which gets ```RuntimeError``` (threads can only be started once) on its ```async with connection``` line.

Any chance to overcome this, am I missing something?

### Details

* OS: Windows 10
* Python version: 3.6 (64-bit)
* aiosqlite version: 0.9.0

**Comment by jreese** [comment]
Generally speaking, you could manually `await connection.__aenter__()` and then `await connection.__aexit__(None, None, None)` when you want to close it.  However, given the single-threaded and non-concurrent implementation underlying aiosqlite, any sort of shared use case with a single connection will need to be done without the use of transactions (ie, don't use `begin()`).  More specifically, if you intend to use connections like this, I would likely recommend using an outer context manager or [ExitStack](https://docs.python.org/3.6/library/contextlib.html#contextlib.ExitStack) to ensure that connections are correctly closed when exceptions occur.

**Comment by tmewett** [comment]
I've just run into this, could you explain why it doesn't work? My understanding was a context manager is just an inert object, so returning it without entering it and using that object should be the same as instantiating it in the `async with`? Is this a weird interaction with Python's refcounter or something?

**Comment by tmewett** [comment]
Wait, no I'm getting a completely different error, and it's my fault. Lol! I thought this was about using a `async with` with the connection in a variable. Sorry!
