### ISSUE TITLE
Expose connection outside context manager

### ISSUE THREAD

**Issue by Snawoot** [jreese/aiosqlite#29]
Hello,

I'm using aiosqlite and it works well for me, but I can suggest useful improvement.

Currently aiosqlite creates thread and connection when user enters created context manager and destroys thread and connection when user leaves context. It means user have to reopen database and run all connection setup pragma's every time I access database. In order to reuse connection and thread I have to invoke `__aenter__` and `__aexit__` directly.

Why connection reuse is important:
* Database open and thread launch adds some overhead.
* Statement cache is discarded when thread and connection is destroyed. Practically, with such context manager it doesn't work.

My practical use case is following: I create some pool of connections and since my `journal_mode` is `WAL`, often reads do not block each other and play well together.

Is it possible to expose connection start/stop as coroutines besides context manager?

**Comment by jreese** [comment]
This was added in v0.10.0.  See the updated readme for expected usage.

**Comment by Snawoot** [comment]
Thank you!
