### ISSUE TITLE
ValueError on db.execute('select...') with parameters

### ISSUE THREAD

**Issue by Didiv** [jreese/aiosqlite#52]
### Description
Raise ValueError exception on execute select statement with parameters.

### Details
Linux 4.4.192-rockchip64/Python 3.6.9/aiosqlite 0.11.0 or
Windows 7 x64/Python 3.8.0/aiosqlite 0.11.00
```
import asyncio
import aiosqlite


async def task1(num):
    async with aiosqlite.connect('test.sqlite') as db:
        await db.execute('''
            create table test (id integer)
            ''')
        await db.execute('''
            insert into test (id) values(?)
            ''', (num))
        cur = await db.execute('''
            select id from test where id = ?
            ''', (num)) # ValueError !!!!!!!!

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(task1(10)))
```

**Comment by jreese** [comment]
I believe the problem is that `(num)` is not a tuple as sqlite is expecting, just an integer wrapped in parens. If you instead change those to `(num,)` to correctly pass a tuple containing the value, then the code works just fine.

As far as I can tell, the exception is coming from sqlite itself.
